language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jameem/docker-react -f ./frontend/Dockerfile.dev .

script:
  - docker run -e CI=true jameem/docker-react npm run test
